### ISSUE TITLE
commonAddedLinesContains

### ISSUE THREAD

**Issue by steprescott** [sogame/danger-plugin-toolbox#271]
I would like to check each line of any added or modified file to see if it contains a `http://` url. However I can't seem to get anything to be flagged up as a warning. I'm currently on `1.22.1` as Peril isn't updated to danger 10.0.0 [yet](https://github.com/danger/peril/issues/470).

Although my regex isn't pro level I have checked using online testers. Is there anything below that you see I'm doing wrong?

```node
import { commonAddedLinesContains } from 'danger-plugin-toolbox'

commonAddedLinesContains(/.*/, /http:\/\//i, file => `The file "${file}" contains insecure URL.`);
```

I've also checked to see if the job, due to it being `async`, needed to be scheduled.
_Note that the messages are added to the PR_
```node
import { danger, schedule, message, warn } from 'danger';
import { commonAddedLinesContains } from 'danger-plugin-toolbox'

schedule(async () => {
  message('Before');
  await commonAddedLinesContains(/.*/, /http:\/\//i, file => `The file "${file}" contains insecure URL.`);
  message('After');
});
```

Thanks in advance.

**Comment by steprescott** [comment]
Thanks for the quick reply and sorry for my slow response. I'll log out what you suggested and then will post it back here. Thanks for the support. I'm glad the regex is working 😄

**Comment by sogame** [comment]
Hi @steprescott, any progress so far? 😇

**Comment by steprescott** [comment]
Sorry, I've been pulled in different directions so not getting a lot of time to look at this. Happy to close the ticket and reopen if it still occurs when I get back onto it.

**Comment by sogame** [comment]
Was more curiosity than concern about having the issue open 😂 
Let me know any progress, happy to try to help if possible :-)
